# Generated by Django 4.1.7 on 2023-03-25 21:47

from django.db import migrations, models
import django.utils.timezone
from datetime import datetime, timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_test_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=15)),
                ('album', models.CharField(max_length=50)),
                ('explicit', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('duration', models.DurationField()),
                ('cover_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='This is a new playlist', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.ImageField(default='www.google.com', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='New Playlist', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('album', models.CharField(max_length=50)),
                ('follows', models.IntegerField()),
                ('songs', models.ManyToManyField(to='main_app.song')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='main_app.song'),
        ),
    ]
