# Generated by Django 4.1.7 on 2023-03-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_song_remove_playlist_name_playlist_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
