# Generated by Django 4.1.7 on 2023-03-25 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_playlist_duration_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(),
        ),
    ]
