# Generated by Django 4.1.7 on 2023-03-25 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_playlist_duration_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=68400)),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=68400)),
        ),
    ]
