# Generated by Django 4.1.7 on 2023-03-27 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_playlist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.URLField(default='https://open.spotify.com/track/7recLQoZdzda5jSusYf1T6?si=7e6d0782a7c04868'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=68400)),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
