# Generated by Django 4.1.7 on 2023-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_song_song_link_alter_playlist_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='createdby',
            field=models.CharField(default='Leoni Torres', max_length=40),
            preserve_default=False,
        ),
    ]
